name: single_item_shared_prefs
description: SharedPreferences/UserDefaults persistent Storage implementation.
version: 0.0.1
homepage: https://github.com/dimitar-zabaznoski/single-item-storage-dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  single_item_storage: ^1.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: ^4.1.0
  equatable: ^2.0.0
  mockito: ^5.0.4

